/**
 * GDL Site Visibility — domain model & seed data
 * Source: public LinkedIn posts (Amdocs Mexico / GDL, Aug 2025 anniversary).
 * Upcoming rows are planning placeholders — confirm with site ops.
 */
window.GDL = {
  site: {
    brand: "GDL",
    name: "Amdocs Guadalajara",
    region: "CALA · Mexico",
    tagline: "Site visibility for hackathons, culture, and talent moments.",
    asOf: "2026-07-27",
  },

  pulse: [
    {
      label: "Site milestone",
      value: "10 yrs",
      detail: "Amdocs Mexico anniversary celebrated in Aug 2025",
    },
    {
      label: "Anniversary program",
      value: "24",
      detail: "Events across ~2 months (hackathons, sports, culture)",
    },
    {
      label: "Gen AI Hackathon",
      value: "CALA",
      detail: "Regional Gen AI Hackathon / Hack-a-Tech at GDL",
    },
    {
      label: "Graduates intake",
      value: "~50",
      detail: "First graduates program cohort launched at GDL",
    },
  ],

  themes: [
    {
      title: "Innovation stage",
      body: "Gen AI Fair, Gen AI Hackathon, and CALA Hack-a-Tech put GDL on the regional innovation map with leadership visibility.",
    },
    {
      title: "People & culture",
      body: "Black & White anniversary party, photography contest, arcade challenges, and escape rooms broaden engagement beyond engineering.",
    },
    {
      title: "Talent pipeline",
      body: "Graduates Program and Ambassadors Club amplify employee voice and create a repeatable story for early-career hiring.",
    },
    {
      title: "Active lifestyle brand",
      body: "Soccer, bowling, kart racing, and step challenges keep site energy visible across social and internal channels.",
    },
  ],

  events: [
    {
      id: "genai-hackathon-2025",
      name: "Amdocs Gen AI Hackathon (GDL)",
      category: "Hackathon",
      status: "Completed",
      when: "Aug 2025",
      sortKey: "2025-08-15",
      audience: "CALA engineering teams",
      highlight:
        "AIvengers placed 3rd / 2nd runner-up; 10th anniversary celebration",
      visibility: "High",
    },
    {
      id: "cala-hack-a-tech-2025",
      name: "CALA Hack-a-Tech 2025",
      category: "Hackathon",
      status: "Completed",
      when: "Aug 2025",
      sortKey: "2025-08-20",
      audience: "CALA + GDL innovators",
      highlight: "Creativity + innovation showcase with top leadership present",
      visibility: "High",
    },
    {
      id: "genai-fair",
      name: "Gen AI Fair",
      category: "Community",
      status: "Completed",
      when: "Aug 2025",
      sortKey: "2025-08-10",
      audience: "Site-wide",
      highlight:
        "Hands-on Gen AI demos and learning sessions during anniversary month",
      visibility: "High",
    },
    {
      id: "bw-anniversary-party",
      name: "Black & White Anniversary Party",
      category: "Culture",
      status: "Completed",
      when: "Aug 2025",
      sortKey: "2025-08-25",
      audience: "Amdocs Mexico",
      highlight: "Flagship celebration for 10 years of Amdocs Mexico / GDL",
      visibility: "High",
    },
    {
      id: "soccer-tournament",
      name: "Soccer Tournament",
      category: "Sports",
      status: "Completed",
      when: "Jul–Aug 2025",
      sortKey: "2025-07-20",
      audience: "Employees",
      highlight: "Site sports tournament during anniversary program",
      visibility: "Medium",
    },
    {
      id: "bowling-tournament",
      name: "Bowling Tournament",
      category: "Sports",
      status: "Completed",
      when: "Jul–Aug 2025",
      sortKey: "2025-07-22",
      audience: "Employees",
      highlight: "Cross-team social competition",
      visibility: "Medium",
    },
    {
      id: "kart-racing",
      name: "Kart Racing Challenge",
      category: "Sports",
      status: "Completed",
      when: "Jul–Aug 2025",
      sortKey: "2025-07-25",
      audience: "Employees",
      highlight: "High-energy outdoor / venue event in anniversary slate",
      visibility: "Medium",
    },
    {
      id: "arcade-videogames",
      name: "Arcade & Videogame Challenges",
      category: "Culture",
      status: "Completed",
      when: "Jul–Aug 2025",
      sortKey: "2025-07-28",
      audience: "Employees",
      highlight: "Casual gaming challenges for site engagement",
      visibility: "Internal",
    },
    {
      id: "escape-rooms",
      name: "Escape Rooms",
      category: "Culture",
      status: "Completed",
      when: "Jul–Aug 2025",
      sortKey: "2025-07-30",
      audience: "Teams",
      highlight: "Team-building puzzle events",
      visibility: "Internal",
    },
    {
      id: "photography-contest",
      name: "Photography Contest",
      category: "Culture",
      status: "Completed",
      when: "Jul–Aug 2025",
      sortKey: "2025-08-05",
      audience: "Employees",
      highlight: "Creative contest tied to anniversary storytelling",
      visibility: "Medium",
    },
    {
      id: "step-challenge",
      name: "Site Step Challenge",
      category: "Sports",
      status: "Completed",
      when: "~45 days · mid-2025",
      sortKey: "2025-07-01",
      audience: "Employees",
      highlight: "Wellness challenge; top finishers near ~500k steps",
      visibility: "Medium",
    },
    {
      id: "graduates-program",
      name: "Graduates Program Launch",
      category: "Talent",
      status: "Recurring",
      when: "2025 launch",
      sortKey: "2025-08-01",
      audience: "Early-career talent",
      highlight: "~50 graduates joined; first-ever GDL graduates cohort",
      visibility: "High",
    },
    {
      id: "ambassadors-club",
      name: "Ambassadors Club Kickoff",
      category: "Talent",
      status: "Recurring",
      when: "2025 launch",
      sortKey: "2025-08-08",
      audience: "Employee ambassadors",
      highlight:
        "Empowers employee voices for site storytelling & recruiting",
      visibility: "Medium",
    },
    {
      id: "leadership-visits",
      name: "Leadership Visits & Hosting",
      category: "Leadership",
      status: "Recurring",
      when: "Ongoing",
      sortKey: "2025-08-12",
      audience: "Executives + site",
      highlight:
        "Hosted leaders (e.g. Gina Chakravarty, Michael Zilberstein, Alon Yampel)",
      visibility: "High",
    },
    {
      id: "genai-hackathon-2026",
      name: "GDL Gen AI Hackathon (next cycle)",
      category: "Hackathon",
      status: "Upcoming",
      when: "TBD 2026",
      sortKey: "2026-08-01",
      audience: "CALA / GDL teams",
      highlight:
        "Placeholder for next annual hackathon — confirm dates with site ops",
      visibility: "High",
    },
    {
      id: "hackathon-internal-att",
      name: "ATT / BSSe Innovation Day @ GDL",
      category: "Hackathon",
      status: "Upcoming",
      when: "Propose · 2026",
      sortKey: "2026-09-01",
      audience: "ATT BSS Evolution teams at GDL",
      highlight:
        "Suggested local visibility event for ATT delivery — align with PI / site calendar",
      visibility: "Internal",
    },
  ],

  checklist: [
    {
      action: "Confirm 2026 Gen AI Hackathon dates",
      owner: "GDL site / innovation",
      why: "Keeps the high-visibility tech brand current",
    },
    {
      action: "Publish ATT/BSSe Innovation Day proposal",
      owner: "ATT delivery leads @ GDL",
      why: "Local product impact story for leadership",
    },
    {
      action: "Refresh Ambassadors Club content calendar",
      owner: "People / ERG",
      why: "Sustains recruiting and culture visibility",
    },
    {
      action: "Capture winners & demos from last hackathon",
      owner: "Comms",
      why: "Reusable assets for PI demos and hiring pages",
    },
  ],

  filters: {
    categories: [
      "All",
      "Hackathon",
      "Sports",
      "Culture",
      "Talent",
      "Leadership",
      "Community",
    ],
    statuses: ["All", "Upcoming", "Completed", "Recurring"],
    visibilities: ["All", "High", "Medium", "Internal"],
  },
};
